import os
from dataclasses import dataclass
from typing import Dict, Optional
from datetime import datetime

from .project_analyzer import (
    ProjectInfo,
    Language,
    Framework,
    ServiceType,
)


@dataclass
class GeneratedIaC:
    dockerfile: Optional[str] = None
    docker_compose: Optional[str] = None
    kubernetes_deployment: Optional[str] = None
    kubernetes_service: Optional[str] = None
    kubernetes_configmap: Optional[str] = None
    helm_values: Optional[str] = None
    github_actions: Optional[str] = None

    def to_dict(self) -> Dict[str, Optional[str]]:
        return {
            "dockerfile": self.dockerfile,
            "docker_compose": self.docker_compose,
            "kubernetes_deployment": self.kubernetes_deployment,
            "kubernetes_service": self.kubernetes_service,
            "kubernetes_configmap": self.kubernetes_configmap,
            "helm_values": self.helm_values,
            "github_actions": self.github_actions,
        }

    def save_to_directory(self, output_dir: str):
        os.makedirs(output_dir, exist_ok=True)

        files = {
            "Dockerfile": self.dockerfile,
            "docker-compose.yml": self.docker_compose,
            "k8s/deployment.yaml": self.kubernetes_deployment,
            "k8s/service.yaml": self.kubernetes_service,
            "k8s/configmap.yaml": self.kubernetes_configmap,
            "helm/values.yaml": self.helm_values,
            ".github/workflows/ci.yml": self.github_actions,
        }

        for filename, content in files.items():
            if content:
                filepath = os.path.join(output_dir, filename)
                os.makedirs(os.path.dirname(filepath), exist_ok=True)
                with open(filepath, "w") as f:
                    f.write(content)


class IaCFromSourceGenerator:
    def __init__(self, project_info: ProjectInfo):
        self.info = project_info

    def generate_all(self) -> GeneratedIaC:
        return GeneratedIaC(
            dockerfile=self.generate_dockerfile(),
            docker_compose=self.generate_docker_compose(),
            kubernetes_deployment=self.generate_kubernetes_deployment(),
            kubernetes_service=self.generate_kubernetes_service(),
            kubernetes_configmap=self.generate_kubernetes_configmap(),
            helm_values=self.generate_helm_values(),
            github_actions=self.generate_github_actions(),
        )

    def generate_dockerfile(self) -> str:
        info = self.info

        if info.language == Language.PYTHON:
            return self._generate_python_dockerfile()
        elif info.language in [Language.JAVASCRIPT, Language.TYPESCRIPT]:
            return self._generate_node_dockerfile()
        elif info.language == Language.GO:
            return self._generate_go_dockerfile()
        else:
            return self._generate_generic_dockerfile()

    def _generate_python_dockerfile(self) -> str:
        info = self.info
        python_version = info.python_version or "3.11"
        port = info.ports[0].port if info.ports else 8000

        base_image = f"python:{python_version}-slim"

        dockerfile = f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Language: Python {python_version}
# Generated: {datetime.now().isoformat()}

# Build stage
FROM {base_image} AS builder

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    libpq-dev \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Production stage
FROM {base_image}

WORKDIR /app

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libpq5 \\
    && rm -rf /var/lib/apt/lists/*

# Copy installed packages from builder
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

# Copy application code
COPY . .

# Create non-root user
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:{port}{info.health_check_path or "/health"}')" || exit 1

# Start command
"""

        if info.start_command:
            dockerfile += f"CMD {self._cmd_to_list(info.start_command)}\n"
        elif Framework.DJANGO in info.frameworks:
            dockerfile += f'CMD ["gunicorn", "--bind", "0.0.0.0:{port}", "{info.name}.wsgi:application"]\n'
        elif Framework.FASTAPI in info.frameworks:
            entry = info.entry_point.replace(".py", "") if info.entry_point else "main"
            dockerfile += f'CMD ["uvicorn", "{entry}:app", "--host", "0.0.0.0", "--port", "{port}"]\n'
        elif Framework.FLASK in info.frameworks:
            entry = info.entry_point.replace(".py", "") if info.entry_point else "app"
            dockerfile += (
                f'CMD ["gunicorn", "--bind", "0.0.0.0:{port}", "{entry}:app"]\n'
            )
        else:
            dockerfile += f'CMD ["python", "{info.entry_point or "main.py"}"]\n'

        return dockerfile

    def _generate_node_dockerfile(self) -> str:
        info = self.info
        node_version = info.node_version or "18"
        port = info.ports[0].port if info.ports else 3000

        is_nextjs = Framework.NEXTJS in info.frameworks

        if is_nextjs:
            return self._generate_nextjs_dockerfile(node_version, port)

        dockerfile = f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Language: Node.js {node_version}
# Generated: {datetime.now().isoformat()}

# Build stage
FROM node:{node_version}-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY . .

# Build if needed
RUN npm run build --if-present

# Production stage
FROM node:{node_version}-alpine

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001

# Copy from builder
COPY --from=builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nodejs:nodejs /app/package*.json ./
COPY --from=builder --chown=nodejs:nodejs /app/dist ./dist 2>/dev/null || true
COPY --from=builder --chown=nodejs:nodejs /app/build ./build 2>/dev/null || true
COPY --from=builder --chown=nodejs:nodejs /app/src ./src 2>/dev/null || true
COPY --from=builder --chown=nodejs:nodejs /app/index.js ./index.js 2>/dev/null || true

USER nodejs

EXPOSE {port}

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:{port}/health || exit 1

CMD ["npm", "start"]
"""
        return dockerfile

    def _generate_nextjs_dockerfile(self, node_version: str, port: int) -> str:
        info = self.info

        return f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Framework: Next.js
# Generated: {datetime.now().isoformat()}

# Dependencies stage
FROM node:{node_version}-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
RUN npm ci

# Builder stage
FROM node:{node_version}-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Runner stage
FROM node:{node_version}-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE {port}

ENV PORT {port}

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:{port}/api/health || exit 1

CMD ["node", "server.js"]
"""

    def _generate_go_dockerfile(self) -> str:
        info = self.info
        go_version = info.go_version or "1.21"
        port = info.ports[0].port if info.ports else 8080

        return f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Language: Go {go_version}
# Generated: {datetime.now().isoformat()}

# Build stage
FROM golang:{go_version}-alpine AS builder

WORKDIR /app

# Install dependencies
RUN apk add --no-cache git ca-certificates

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Production stage
FROM scratch

# Copy CA certificates
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Copy binary
COPY --from=builder /app/main /main

EXPOSE {port}

ENTRYPOINT ["/main"]
"""

    def _generate_generic_dockerfile(self) -> str:
        info = self.info
        port = info.ports[0].port if info.ports else 8080

        return f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

FROM ubuntu:22.04

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy application
COPY . .

EXPOSE {port}

CMD ["bash"]
"""

    def generate_docker_compose(self) -> str:
        info = self.info
        port = info.ports[0].port if info.ports else 8000

        compose = f'''# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

version: "3.8"

services:
  {info.name}:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{port}:{port}"
    environment:
'''

        for env in info.env_vars:
            default = env.default or ""
            compose += f"      - {env.name}={default}\n"

        compose += f"      - PORT={port}\n"

        if info.databases:
            compose += "    depends_on:\n"
            for db in info.databases:
                compose += f"      - {db.type}\n"

        compose += "    restart: unless-stopped\n"
        compose += "    networks:\n"
        compose += f"      - {info.name}-network\n"

        if info.health_check_path:
            compose += f"""    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{port}{info.health_check_path}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
"""

        for db in info.databases:
            if db.type == "postgresql":
                compose += f"""
  {db.type}:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB={info.name}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - {info.name}-network
"""
            elif db.type == "mysql":
                compose += f"""
  {db.type}:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE={info.name}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - {info.name}-network
"""
            elif db.type == "mongodb":
                compose += f"""
  {db.type}:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - {info.name}-network
"""
            elif db.type == "redis":
                compose += f"""
  {db.type}:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - {info.name}-network
"""

        compose += f"""
networks:
  {info.name}-network:
    driver: bridge
"""

        if info.databases:
            compose += "\nvolumes:\n"
            for db in info.databases:
                if db.type == "postgresql":
                    compose += "  postgres-data:\n"
                elif db.type == "mysql":
                    compose += "  mysql-data:\n"
                elif db.type == "mongodb":
                    compose += "  mongo-data:\n"

        return compose

    def generate_kubernetes_deployment(self) -> str:
        info = self.info
        port = info.ports[0].port if info.ports else 8000

        if info.service_type == ServiceType.WORKER:
            cpu_request, cpu_limit = "100m", "500m"
            mem_request, mem_limit = "128Mi", "512Mi"
        else:
            cpu_request, cpu_limit = "100m", "1000m"
            mem_request, mem_limit = "128Mi", "1Gi"

        deployment = f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {info.name}
  labels:
    app: {info.name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {info.name}
  template:
    metadata:
      labels:
        app: {info.name}
    spec:
      containers:
      - name: {info.name}
        image: {info.name}:latest
        ports:
        - containerPort: {port}
        env:
"""

        for env in info.env_vars:
            if env.default:
                deployment += f'''        - name: {env.name}
          value: "{env.default}"
'''
            else:
                deployment += f"""        - name: {env.name}
          valueFrom:
            secretKeyRef:
              name: {info.name}-secrets
              key: {env.name.lower()}
"""

        deployment += f'''        resources:
          requests:
            cpu: "{cpu_request}"
            memory: "{mem_request}"
          limits:
            cpu: "{cpu_limit}"
            memory: "{mem_limit}"
'''

        if info.health_check_path:
            deployment += f"""        livenessProbe:
          httpGet:
            path: {info.health_check_path}
            port: {port}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: {info.health_check_path}
            port: {port}
          initialDelaySeconds: 5
          periodSeconds: 10
"""

        deployment += """      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
"""

        return deployment

    def generate_kubernetes_service(self) -> str:
        info = self.info
        port = info.ports[0].port if info.ports else 8000

        return f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

apiVersion: v1
kind: Service
metadata:
  name: {info.name}
  labels:
    app: {info.name}
spec:
  type: ClusterIP
  ports:
  - port: {port}
    targetPort: {port}
    protocol: TCP
    name: http
  selector:
    app: {info.name}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {info.name}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {info.name}.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {info.name}
            port:
              number: {port}
"""

    def generate_kubernetes_configmap(self) -> str:
        info = self.info

        configmap = f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {info.name}-config
data:
"""

        for env in info.env_vars:
            if env.default and not self._is_sensitive(env.name):
                configmap += f'  {env.name}: "{env.default}"\n'

        return configmap

    def generate_helm_values(self) -> str:
        info = self.info
        port = info.ports[0].port if info.ports else 8000

        values = f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

replicaCount: 2

image:
  repository: {info.name}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: {port}

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: {info.name}.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
"""

        for env in info.env_vars:
            if env.default and not self._is_sensitive(env.name):
                values += f'  {env.name}: "{env.default}"\n'

        values += """
secrets:
"""
        for env in info.env_vars:
            if self._is_sensitive(env.name):
                values += f'  {env.name}: ""\n'

        if info.health_check_path:
            values += f"""
probes:
  liveness:
    path: {info.health_check_path}
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    path: {info.health_check_path}
    initialDelaySeconds: 5
    periodSeconds: 10
"""

        return values

    def generate_github_actions(self) -> str:
        info = self.info

        workflow = f"""# Auto-generated by Kube-Tofu
# Project: {info.name}
# Generated: {datetime.now().isoformat()}

name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{{{ github.repository }}}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
"""

        if info.language == Language.PYTHON:
            workflow += f"""
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '{info.python_version or "3.11"}'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: pytest --cov=./ --cov-report=xml
"""
        elif info.language in [Language.JAVASCRIPT, Language.TYPESCRIPT]:
            workflow += f"""
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '{info.node_version or "18"}'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
"""
        elif info.language == Language.GO:
            workflow += f"""
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '{info.go_version or "1.21"}'
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build
      run: go build -v ./...
"""

        workflow += """
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
"""

        return workflow

    def _cmd_to_list(self, cmd: str) -> str:
        parts = cmd.split()
        return str(parts)

    def _is_sensitive(self, name: str) -> bool:
        sensitive_patterns = [
            "password",
            "secret",
            "key",
            "token",
            "api_key",
            "apikey",
            "auth",
            "credential",
            "private",
        ]
        name_lower = name.lower()
        return any(p in name_lower for p in sensitive_patterns)
