import os

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

app = typer.Typer(help="Initialize a new Kube-Tofu project")
console = Console()


@app.callback(invoke_without_command=True)
def init_project(
    provider: str = typer.Option(
        "arvancloud", "--provider", "-p", help="Cloud provider"
    ),
    name: str = typer.Option(None, "--name", "-n", help="Project name"),
    directory: str = typer.Option(".", "--dir", "-d", help="Project directory"),
):
    console.print(
        Panel.fit(
            "[bold blue]Kube-Tofu Project Initialization[/bold blue]",
            title="🎉 Welcome",
        )
    )

    if not name:
        name = Prompt.ask(
            "Project name",
            default=os.path.basename(os.getcwd()),
        )

    providers = ["arvancloud", "aws", "gcp", "azure", "hetzner"]
    console.print("\n[bold]Available providers:[/bold]")
    for i, p in enumerate(providers, 1):
        marker = "→" if p == provider else " "
        console.print(f"  {marker} {i}. {p}")

    api_key = Prompt.ask(
        f"\n{provider.title()} API Key",
        password=True,
    )

    if provider == "arvancloud":
        regions = {
            "1": "ir-thr-at1 (Tehran - Azadi Tower)",
            "2": "ir-thr-mn1 (Tehran - Milad Tower)",
            "3": "ir-tbz-at1 (Tabriz)",
            "4": "nl-ams-su1 (Amsterdam)",
            "5": "de-fra-su1 (Frankfurt)",
        }
        console.print("\n[bold]Available regions:[/bold]")
        for k, v in regions.items():
            console.print(f"  {k}. {v}")
        region_choice = Prompt.ask("Select region", default="1")
        region = list(regions.values())[int(region_choice) - 1].split()[0]
    else:
        region = Prompt.ask("Region", default="us-east-1")

    project_dir = (
        os.path.join(directory, name)
        if name != os.path.basename(os.getcwd())
        else directory
    )

    console.print(f"\n[bold]Creating project in:[/bold] {os.path.abspath(project_dir)}")

    dirs = ["modules", "environments/dev", "environments/staging", "environments/prod"]
    for d in dirs:
        os.makedirs(os.path.join(project_dir, d), exist_ok=True)

    config_content = f"""# Kube-Tofu Configuration
# Generated by kubetofu init

project:
  name: {name}
  version: "1.0.0"

provider:
  name: {provider}
  region: {region}

agents:
  planner:
    enabled: true
  security:
    enabled: true
    compliance:
      - CIS
      - SOC2
  cost:
    enabled: true
    budget_alert: 100000000  # IRR
  deployment:
    enabled: true
    auto_approve: false
  monitoring:
    enabled: true

terraform:
  version: ">= 1.6.0"
  backend:
    type: local
    # For remote backend:
    # type: arvancloud
    # bucket: "my-tfstate-bucket"

environments:
  - name: dev
    auto_approve: true
  - name: staging
    requires_approval: true
  - name: prod
    requires_approval: true
    approval_count: 2
"""

    with open(os.path.join(project_dir, "kubetofu.yaml"), "w") as f:
        f.write(config_content)

    env_content = f"""# Kube-Tofu Environment Variables
# NEVER commit this file to version control

{provider.upper()}_API_KEY={api_key}
{provider.upper()}_REGION={region}

# LLM Configuration (optional)
# ANTHROPIC_API_KEY=your-key
# OPENAI_API_KEY=your-key
"""

    with open(os.path.join(project_dir, ".env"), "w") as f:
        f.write(env_content)

    gitignore_content = """# Kube-Tofu
.env
*.tfstate
*.tfstate.*
.terraform/
*.tfvars
crash.log

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""

    with open(os.path.join(project_dir, ".gitignore"), "w") as f:
        f.write(gitignore_content)

    main_tf = f"""# Kube-Tofu Project: {name}
# Provider: {provider}

terraform {{
  required_version = ">= 1.6.0"
  
  required_providers {{
    arvancloud = {{
      source  = "arvancloud/iaas"
      version = ">= 0.6.0"
    }}
  }}
}}

provider "arvancloud" {{
  api_key = var.arvan_api_key
  region  = var.arvan_region
}}

variable "arvan_api_key" {{
  type        = string
  description = "ArvanCloud API Key"
  sensitive   = true
}}

variable "arvan_region" {{
  type        = string
  description = "ArvanCloud region"
  default     = "{region}"
}}

# Add your infrastructure resources below
# Or use kubetofu plan to generate them from natural language
"""

    with open(os.path.join(project_dir, "main.tf"), "w") as f:
        f.write(main_tf)

    console.print("\n[bold green]✓ Project initialized successfully![/bold green]\n")

    console.print("[bold]Project structure:[/bold]")
    console.print(f"  {name}/")
    console.print("  ├── kubetofu.yaml    # Kube-Tofu configuration")
    console.print("  ├── main.tf          # Main Terraform file")
    console.print("  ├── .env             # Environment variables")
    console.print("  ├── .gitignore       # Git ignore rules")
    console.print("  ├── modules/         # Reusable modules")
    console.print("  └── environments/    # Environment configs")
    console.print("      ├── dev/")
    console.print("      ├── staging/")
    console.print("      └── prod/")

    console.print("\n[bold]Next steps:[/bold]")
    console.print("  1. cd " + name)
    console.print('  2. kubetofu plan "Your infrastructure description"')
    console.print("  3. kubetofu apply")
    console.print("\n  Or start an AI chat session:")
    console.print("  kubetofu chat")
