import logging
from typing import Any, Dict, List, Tuple

import yaml

from generators.base import (
    BaseGenerator,
    ErrorCategory,
    GenerationContext,
    GenerationResult,
    IaCType,
    ValidationError,
)

logger = logging.getLogger(__name__)


class KubernetesGenerator(BaseGenerator):
    iac_type = IaCType.KUBERNETES

    def _setup_validators(self) -> None:
        self.validators = [
            self._validate_api_versions,
            self._validate_labels,
        ]

    def generate(self, context: GenerationContext) -> GenerationResult:
        import time

        start_time = time.time()

        config = self._parse_config(context)

        manifests = []

        if config.get("namespace"):
            manifests.append(self._generate_namespace(config))

        manifests.append(self._generate_configmap(config))
        manifests.append(self._generate_secret(config))
        manifests.append(self._generate_deployment(config))
        manifests.append(self._generate_service(config))

        if config.get("ingress", {}).get("enabled"):
            manifests.append(self._generate_ingress(config))

        if config.get("autoscaling", {}).get("enabled"):
            manifests.append(self._generate_hpa(config))

        if config.get("pdb", {}).get("enabled"):
            manifests.append(self._generate_pdb(config))

        if config.get("networkPolicy", {}).get("enabled"):
            manifests.append(self._generate_networkpolicy(config))

        code = "---\n".join(
            [
                yaml.dump(m, default_flow_style=False, sort_keys=False)
                for m in manifests
                if m
            ]
        )

        header = f"""# Auto-generated by Kube-Tofu
# {context.natural_language_request}
#
# Apply with: kubectl apply -f <filename>.yaml
---
"""
        code = header + code

        result = GenerationResult.create(
            iac_type=self.iac_type,
            code=code,
            generation_time=time.time() - start_time,
        )

        return result

    def validate_syntax(self, code: str) -> Tuple[bool, List[ValidationError]]:
        errors = []

        try:
            documents = list(yaml.safe_load_all(code))

            for i, doc in enumerate(documents):
                if doc is None:
                    continue

                if not isinstance(doc, dict):
                    errors.append(
                        ValidationError(
                            category=ErrorCategory.SYNTAX_INVALID_TOKEN,
                            message=f"Document {i + 1} is not a valid Kubernetes manifest",
                        )
                    )
                    continue

                if "apiVersion" not in doc:
                    errors.append(
                        ValidationError(
                            category=ErrorCategory.CONFIG_MISSING_REQUIRED,
                            message=f"Document {i + 1} missing 'apiVersion'",
                        )
                    )

                if "kind" not in doc:
                    errors.append(
                        ValidationError(
                            category=ErrorCategory.CONFIG_MISSING_REQUIRED,
                            message=f"Document {i + 1} missing 'kind'",
                        )
                    )

        except yaml.YAMLError as e:
            errors.append(
                ValidationError(
                    category=ErrorCategory.SYNTAX_INVALID_TOKEN,
                    message=f"Invalid YAML: {e}",
                )
            )
            return False, errors

        return len(errors) == 0, errors

    def validate_semantics(self, code: str) -> Tuple[bool, List[ValidationError]]:
        errors = []

        try:
            documents = list(yaml.safe_load_all(code))

            for doc in documents:
                if doc is None:
                    continue

                kind = doc.get("kind", "")

                if kind == "Deployment":
                    spec = doc.get("spec", {})
                    if not spec.get("selector"):
                        errors.append(
                            ValidationError(
                                category=ErrorCategory.CONFIG_MISSING_REQUIRED,
                                message="Deployment missing selector",
                            )
                        )
                    if not spec.get("template"):
                        errors.append(
                            ValidationError(
                                category=ErrorCategory.CONFIG_MISSING_REQUIRED,
                                message="Deployment missing template",
                            )
                        )

                if kind == "Service":
                    spec = doc.get("spec", {})
                    if not spec.get("ports"):
                        errors.append(
                            ValidationError(
                                category=ErrorCategory.CONFIG_MISSING_REQUIRED,
                                message="Service missing ports",
                            )
                        )

        except Exception as e:
            logger.warning(f"Semantic validation error: {e}")

        return len([e for e in errors if e.severity == "error"]) == 0, errors

    def _validate_api_versions(self, code: str) -> Tuple[bool, List[ValidationError]]:
        errors = []
        deprecated_apis = {
            "extensions/v1beta1": "Use apps/v1 instead",
            "apps/v1beta1": "Use apps/v1 instead",
            "apps/v1beta2": "Use apps/v1 instead",
        }

        for api, suggestion in deprecated_apis.items():
            if api in code:
                errors.append(
                    ValidationError(
                        category=ErrorCategory.CONFIG_DEPRECATED,
                        message=f"Deprecated API version: {api}",
                        suggestion=suggestion,
                        severity="warning",
                    )
                )

        return True, errors

    def _validate_labels(self, code: str) -> Tuple[bool, List[ValidationError]]:
        errors = []

        recommended_labels = [
            "app.kubernetes.io/name",
            "app.kubernetes.io/instance",
            "app.kubernetes.io/version",
        ]

        for label in recommended_labels:
            if label not in code:
                errors.append(
                    ValidationError(
                        category=ErrorCategory.CONFIG_MISSING_REQUIRED,
                        message=f"Missing recommended label: {label}",
                        severity="info",
                    )
                )

        return True, errors

    def _parse_config(self, context: GenerationContext) -> Dict[str, Any]:
        config = {
            "name": "app",
            "namespace": None,
            "replicas": 3 if "production" in context.environment else 1,
            "image": {
                "repository": "nginx",
                "tag": "latest",
            },
            "ports": [{"name": "http", "containerPort": 80}],
            "service": {
                "type": "ClusterIP",
                "port": 80,
            },
            "resources": {
                "limits": {"cpu": "500m", "memory": "512Mi"},
                "requests": {"cpu": "100m", "memory": "128Mi"},
            },
            "ingress": {"enabled": False},
            "autoscaling": {"enabled": False, "minReplicas": 1, "maxReplicas": 10},
            "pdb": {"enabled": False},
            "networkPolicy": {"enabled": False},
            "labels": {
                "app.kubernetes.io/name": "app",
                "app.kubernetes.io/managed-by": "kubetofu",
            },
        }

        request = context.natural_language_request.lower()

        for service in context.services:
            config["name"] = service.lower().replace(" ", "-")
            break

        if "production" in context.environment or "prod" in request:
            config["replicas"] = 3
            config["autoscaling"]["enabled"] = True
            config["pdb"]["enabled"] = True

        if "ingress" in request or "external" in request:
            config["ingress"]["enabled"] = True

        if "network policy" in request or "secure" in request:
            config["networkPolicy"]["enabled"] = True

        return config

    def _generate_namespace(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "v1",
            "kind": "Namespace",
            "metadata": {
                "name": config["namespace"],
                "labels": config["labels"],
            },
        }

    def _generate_configmap(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "data": {
                "LOG_LEVEL": "info",
            },
        }

    def _generate_secret(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "type": "Opaque",
            "data": {},
        }

    def _generate_deployment(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "spec": {
                "replicas": config["replicas"],
                "selector": {
                    "matchLabels": {
                        "app.kubernetes.io/name": config["name"],
                    },
                },
                "template": {
                    "metadata": {
                        "labels": {
                            "app.kubernetes.io/name": config["name"],
                        },
                    },
                    "spec": {
                        "containers": [
                            {
                                "name": config["name"],
                                "image": f"{config['image']['repository']}:{config['image']['tag']}",
                                "ports": config["ports"],
                                "resources": config["resources"],
                                "livenessProbe": {
                                    "httpGet": {"path": "/health", "port": "http"},
                                    "initialDelaySeconds": 30,
                                    "periodSeconds": 10,
                                },
                                "readinessProbe": {
                                    "httpGet": {"path": "/ready", "port": "http"},
                                    "initialDelaySeconds": 5,
                                    "periodSeconds": 5,
                                },
                                "envFrom": [
                                    {"configMapRef": {"name": config["name"]}},
                                    {
                                        "secretRef": {
                                            "name": config["name"],
                                            "optional": True,
                                        }
                                    },
                                ],
                            }
                        ],
                    },
                },
            },
        }

    def _generate_service(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "spec": {
                "type": config["service"]["type"],
                "ports": [
                    {
                        "port": config["service"]["port"],
                        "targetPort": "http",
                        "protocol": "TCP",
                        "name": "http",
                    }
                ],
                "selector": {
                    "app.kubernetes.io/name": config["name"],
                },
            },
        }

    def _generate_ingress(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "Ingress",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
                "annotations": {
                    "nginx.ingress.kubernetes.io/rewrite-target": "/",
                },
            },
            "spec": {
                "rules": [
                    {
                        "host": f"{config['name']}.example.com",
                        "http": {
                            "paths": [
                                {
                                    "path": "/",
                                    "pathType": "Prefix",
                                    "backend": {
                                        "service": {
                                            "name": config["name"],
                                            "port": {
                                                "number": config["service"]["port"]
                                            },
                                        },
                                    },
                                }
                            ],
                        },
                    }
                ],
            },
        }

    def _generate_hpa(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "autoscaling/v2",
            "kind": "HorizontalPodAutoscaler",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "spec": {
                "scaleTargetRef": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "name": config["name"],
                },
                "minReplicas": config["autoscaling"]["minReplicas"],
                "maxReplicas": config["autoscaling"]["maxReplicas"],
                "metrics": [
                    {
                        "type": "Resource",
                        "resource": {
                            "name": "cpu",
                            "target": {
                                "type": "Utilization",
                                "averageUtilization": 80,
                            },
                        },
                    }
                ],
            },
        }

    def _generate_pdb(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "policy/v1",
            "kind": "PodDisruptionBudget",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "spec": {
                "minAvailable": "50%",
                "selector": {
                    "matchLabels": {
                        "app.kubernetes.io/name": config["name"],
                    },
                },
            },
        }

    def _generate_networkpolicy(self, config: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {
                "name": config["name"],
                "labels": config["labels"],
            },
            "spec": {
                "podSelector": {
                    "matchLabels": {
                        "app.kubernetes.io/name": config["name"],
                    },
                },
                "policyTypes": ["Ingress", "Egress"],
                "ingress": [
                    {
                        "from": [{"podSelector": {}}],
                        "ports": [
                            {"protocol": "TCP", "port": config["service"]["port"]}
                        ],
                    }
                ],
                "egress": [
                    {"to": [{"podSelector": {}}]},
                    {
                        "to": [
                            {
                                "namespaceSelector": {},
                                "podSelector": {"matchLabels": {"k8s-app": "kube-dns"}},
                            }
                        ],
                        "ports": [{"protocol": "UDP", "port": 53}],
                    },
                ],
            },
        }
